version: "1.0"

services:
  app:
    build: .
    image: ${DOCKER_USER}/catalog-service:${IMAGE_TAG}
    container_name: catalog-app
    ports:
      - "8082:8082"
    networks:
      - micro-net
    restart: on-failure

    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: ${DB_URL}
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASS}

      SPRING_AWS_ACCESS_KEY: ${AWS_ACCESS_KEY}
      SPRING_AWS_SECRET_KEY: ${AWS_SECRET_KEY}
      SPRING_AWS_BUCKET_NAME: ${AWS_BUCKET_NAME}
      SPRING_AWS_REGION_NAME: ${AWS_REGION_NAME}
      EUREKA_URL: ${EUREKA_URL}

networks:
  micro-net:
    external: true