spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: auth-service
              uri: lb://AUTH-SERVICE
              predicates:
                - Path=/auth-service/**

            - id: catalog-service
              uri: lb://CATALOG-SERVICE
              predicates:
                - Path=/admin/**, /api/books/**

            - id: cart-service
              uri: lb://CART-SERVICE
              predicates:
                - Path=/cart/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URL}

server:
  port: 8080