spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: auth-service
              uri: lb://AUTH-SERVICE
              predicates:
                - Path=/auth-service/**

            - id: catalog-service
              uri: lb://CATALOG-SERVICE
              predicates:
                - Path=/catalog-service/**

            - id: cart-service
              uri: lb://CART-SERVICE
              predicates:
                - Path=/cart-service/**

            - id : order-service
              uri: lb://ORDER-SERVICE
              predicates:
                - Path=/order-service/**

            - id: payment-service
              uri: lb://PAYMENT-SERVICE
              predicates:
                - Path=/payment-service/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URL}

server:
  port: 8080