spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: auth-service
#              http://localhost:8082               this is for local testing
              uri: lb://AUTH-SERVICE:8080
              predicates:
                - Path=/auth/**, /user/**

            - id: catelog-serivce
              uri:
                lb://CATALOG-SERVICE:8082
#                http://localhost:8082            this is for local testign
              predicates:
                - Path=/admin/**, /api/books/**
          globalcors:
            cors-configurations:
              '[/**]':
                allowed-origins:
                  - "http://localhost:5173"
                allowed-methods:
                  - GET
                  - POST
                  - PUT
                  - DELETE
                  - OPTIONS
                allowed-headers:
                  - "*"
                allow-credentials: true


server:
  port: 9000

eureka:
  client:
    service-url:
      defaultZone: http://service-registry:8085/eureka
  instance:
    prefer-ip-address: true

logging:
  level:
    root: error
    org.booknest.apigateway: debug