version: '2.0'

services:
  app:
    build: .
    image: ${DOCKER_USER}/service-registry:${IMAGE_TAG}
    container_name: service-registry
    ports:
      - "9000:9000"

    restart: on-failure

    networks:
      - micro-net

networks:
  micro-net:
    external: true