spring:
  application:
    name: cart-service

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}


  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        ddl-auto: update


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URL}


server:
  port: 8084
  servlet:
    context-path: /cart-service

jwt:
  secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970

logging:
  level:
    org.booknest.cartservice: debug
    root: error