name: Deploy

on:
  push:
    branches:
      - feature/cart-service

jobs:
  deploy:
    runs-on: ubuntu-latest   # GitHub runner (temporary machine)

    steps:

      # 📥 Step 1: Get your code from repo
      - name: Checkout Code
        uses: actions/checkout@v4

      # 🐳 Step 2: Login to Docker Hub securely
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASS }}" | docker login -u "${{ secrets.DOCKER_USER }}" --password-stdin

      # 🏗️ Step 3: Build Docker image using your Dockerfile
      - name: Build Docker Image
        run: docker build -t ${{ secrets.DOCKER_USER }}/cart-service:${{ github.sha }} ./cart-service

      # 📤 Step 4: Push image to Docker Hub
      - name: Push Docker Image
        run: docker push ${{ secrets.DOCKER_USER }}/cart-service:${{ github.sha }}         # remove this ./cart-service

      # 🚀 Step 5: Deploy on EC2 via SSH
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST}}
          username: ubuntu   # or ec2-user (depends on AMI)
          key: ${{ secrets.EC2_KEY}}

          script: |
            # 🛑 Stop old container if running
            docker stop cart-service || true

            # stop and Remove old container
            docker rm cart-service || true

            # 📥 Pull latest image from Docker Hub
            docker pull ${{ secrets.DOCKER_USER }}/cart-service:${{ github.sha }}

            # 🚀 Run new container with environment variables
            docker run -p 8084:8084 \
              --name cart-service \
              -e DB_URL="${{ secrets.DB_URL }}" \
              -e DB_USER="${{ secrets.DB_USER }}" \
              -e DB_PASS="${{ secrets.DB_PASS }}" \
              -e EUREKA_URL="${{ secrets.EUREKA_URL }}" \
              ${{ secrets.DOCKER_USER }}/cart-service:${{ github.sha }}